<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="12" hostname="LAPTOP-I9NSEBS5" name="pytest" skipped="0" tests="32" time="0.217" timestamp="2021-02-18T19:08:30.939804"><testcase classname="code.test_combat" file="code\test_combat.py" line="25" name="test_attack_rat_king_OOP" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_combat" file="code\test_combat.py" line="20" name="test_attack_rat_king_noOOP" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_combat" file="code\test_combat.py" line="15" name="test_playerattack_belowmax" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_combat" file="code\test_combat.py" line="10" name="test_playerattack_notzero" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves" file="code\test_moves.py" line="21" name="test_move_down_failure" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

+---+---+---+---+---+---+---+---+
|T/H|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   | T |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | T |   |   |
+---+---+---+---+---+---+---+---+
|   | T |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | T |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | K |
+---+---+---+---+---+---+---+---+

Cannot move DOWN

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves" file="code\test_moves.py" line="16" name="test_move_down_success" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

+---+---+---+---+---+---+---+---+
|T/H|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   | T |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | T |   |   |
+---+---+---+---+---+---+---+---+
|   | T |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | T |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | K |
+---+---+---+---+---+---+---+---+


</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves" file="code\test_moves.py" line="39" name="test_move_left_failure" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

+---+---+---+---+---+---+---+---+
|T/H|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   | T |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | T |   |   |
+---+---+---+---+---+---+---+---+
|   | T |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | T |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | K |
+---+---+---+---+---+---+---+---+

Cannot move LEFT

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves" file="code\test_moves.py" line="34" name="test_move_left_success" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

+---+---+---+---+---+---+---+---+
|T/H|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   | T |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | T |   |   |
+---+---+---+---+---+---+---+---+
|   | T |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | T |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | K |
+---+---+---+---+---+---+---+---+


</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves" file="code\test_moves.py" line="30" name="test_move_right_failure" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

+---+---+---+---+---+---+---+---+
|T/H|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   | T |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | T |   |   |
+---+---+---+---+---+---+---+---+
|   | T |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | T |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | K |
+---+---+---+---+---+---+---+---+

Cannot move RIGHT

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves" file="code\test_moves.py" line="25" name="test_move_right_success" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

+---+---+---+---+---+---+---+---+
|T/H|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   | T |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | T |   |   |
+---+---+---+---+---+---+---+---+
|   | T |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | T |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | K |
+---+---+---+---+---+---+---+---+


</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves" file="code\test_moves.py" line="12" name="test_move_up_failure" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

+---+---+---+---+---+---+---+---+
|T/H|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   | T |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | T |   |   |
+---+---+---+---+---+---+---+---+
|   | T |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | T |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | K |
+---+---+---+---+---+---+---+---+

Cannot move UP

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves" file="code\test_moves.py" line="7" name="test_move_up_success" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

+---+---+---+---+---+---+---+---+
|T/H|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   | T |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | T |   |   |
+---+---+---+---+---+---+---+---+
|   | T |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | T |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | K |
+---+---+---+---+---+---+---+---+


</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves_and_save" file="code\test_moves_and_save.py" line="22" name="test_move_down_failure" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

+---+---+---+---+---+---+---+---+
|T/H|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   | T |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | T |   |   |
+---+---+---+---+---+---+---+---+
|   | T |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | T |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | K |
+---+---+---+---+---+---+---+---+

Cannot move DOWN

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves_and_save" file="code\test_moves_and_save.py" line="17" name="test_move_down_success" time="0.003"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

+---+---+---+---+---+---+---+---+
|T/H|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   | T |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | T |   |   |
+---+---+---+---+---+---+---+---+
|   | T |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | T |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | K |
+---+---+---+---+---+---+---+---+


</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves_and_save" file="code\test_moves_and_save.py" line="40" name="test_move_left_failure" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

+---+---+---+---+---+---+---+---+
|T/H|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   | T |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | T |   |   |
+---+---+---+---+---+---+---+---+
|   | T |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | T |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | K |
+---+---+---+---+---+---+---+---+

Cannot move LEFT

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves_and_save" file="code\test_moves_and_save.py" line="35" name="test_move_left_success" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

+---+---+---+---+---+---+---+---+
|T/H|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   | T |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | T |   |   |
+---+---+---+---+---+---+---+---+
|   | T |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | T |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | K |
+---+---+---+---+---+---+---+---+


</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves_and_save" file="code\test_moves_and_save.py" line="31" name="test_move_right_failure" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

+---+---+---+---+---+---+---+---+
|T/H|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   | T |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | T |   |   |
+---+---+---+---+---+---+---+---+
|   | T |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | T |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | K |
+---+---+---+---+---+---+---+---+

Cannot move RIGHT

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves_and_save" file="code\test_moves_and_save.py" line="26" name="test_move_right_success" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

+---+---+---+---+---+---+---+---+
|T/H|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   | T |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | T |   |   |
+---+---+---+---+---+---+---+---+
|   | T |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | T |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | K |
+---+---+---+---+---+---+---+---+


</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves_and_save" file="code\test_moves_and_save.py" line="13" name="test_move_up_failure" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

+---+---+---+---+---+---+---+---+
|T/H|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   | T |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | T |   |   |
+---+---+---+---+---+---+---+---+
|   | T |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | T |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | K |
+---+---+---+---+---+---+---+---+

Cannot move UP

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves_and_save" file="code\test_moves_and_save.py" line="8" name="test_move_up_success" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

+---+---+---+---+---+---+---+---+
|T/H|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   | T |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | T |   |   |
+---+---+---+---+---+---+---+---+
|   | T |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | T |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | K |
+---+---+---+---+---+---+---+---+


</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves_and_save" file="code\test_moves_and_save.py" line="64" name="test_save_game_day" time="0.001"><failure message="FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'">def test_save_game_day():#Tests if the correct day is saved
        rat_hp = 10
        hero_hp = 20
        day = 1 #By default day = 1
        x = 0
        y = 0
        state = 0
&gt;       result = save_game(game)

code\test_moves_and_save.py:72: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

game = [0, [[1, 0, 0, 0, 0, 0, ...], [0, 0, 0, 1, 0, 0, ...], [0, 0, 0, 0, 0, 1, ...], [0, 1, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], ...], [2, 4, 1, 20], 1, [1, 3, 1, 10], 0, ...]

    def save_game(game):
        rat_hp = str(game[RAT_INDEX][3])
        hero_hp = str(game[HERO_INDEX][3])
        day = str(game[DAY_INDEX])
        x = str(game[X_INDEX])
        y = str(game[Y_INDEX])
        state = str(game[STATE_INDEX])
    
        game_data = [state, hero_hp, day, rat_hp, x, y]
&gt;       game_file = open(GAME_FILE_NAME, 'w')
E       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'

code\new_save_exit_game.py:200: FileNotFoundError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves_and_save" file="code\test_moves_and_save.py" line="44" name="test_save_game_game_state" time="0.001"><failure message="FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'">def test_save_game_game_state():#Tests if the correct game state is saved
        rat_hp = 10
        hero_hp = 20
        day = 1
        x = 0
        y = 0
        state = 0 #By default game state is 0
&gt;       result = save_game(game)

code\test_moves_and_save.py:52: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

game = [0, [[1, 0, 0, 0, 0, 0, ...], [0, 0, 0, 1, 0, 0, ...], [0, 0, 0, 0, 0, 1, ...], [0, 1, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], ...], [2, 4, 1, 20], 1, [1, 3, 1, 10], 0, ...]

    def save_game(game):
        rat_hp = str(game[RAT_INDEX][3])
        hero_hp = str(game[HERO_INDEX][3])
        day = str(game[DAY_INDEX])
        x = str(game[X_INDEX])
        y = str(game[Y_INDEX])
        state = str(game[STATE_INDEX])
    
        game_data = [state, hero_hp, day, rat_hp, x, y]
&gt;       game_file = open(GAME_FILE_NAME, 'w')
E       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'

code\new_save_exit_game.py:200: FileNotFoundError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves_and_save" file="code\test_moves_and_save.py" line="54" name="test_save_game_hero_hp" time="0.001"><failure message="FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'">def test_save_game_hero_hp():#Tests if the correct hero hp is saved
        rat_hp = 10
        hero_hp = 20 #By default hero hp starts at 20
        day = 1
        x = 0
        y = 0
        state = 0
&gt;       result = save_game(game)

code\test_moves_and_save.py:62: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

game = [0, [[1, 0, 0, 0, 0, 0, ...], [0, 0, 0, 1, 0, 0, ...], [0, 0, 0, 0, 0, 1, ...], [0, 1, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], ...], [2, 4, 1, 20], 1, [1, 3, 1, 10], 0, ...]

    def save_game(game):
        rat_hp = str(game[RAT_INDEX][3])
        hero_hp = str(game[HERO_INDEX][3])
        day = str(game[DAY_INDEX])
        x = str(game[X_INDEX])
        y = str(game[Y_INDEX])
        state = str(game[STATE_INDEX])
    
        game_data = [state, hero_hp, day, rat_hp, x, y]
&gt;       game_file = open(GAME_FILE_NAME, 'w')
E       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'

code\new_save_exit_game.py:200: FileNotFoundError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves_and_save" file="code\test_moves_and_save.py" line="74" name="test_save_game_rat_hp" time="0.001"><failure message="FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'">def test_save_game_rat_hp():#Tests if the correct rat hp is saved
        rat_hp = 10 #By default rat hp = 10
        hero_hp = 20
        day = 1
        x = 0
        y = 0
        state = 0
&gt;       result = save_game(game)

code\test_moves_and_save.py:82: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

game = [0, [[1, 0, 0, 0, 0, 0, ...], [0, 0, 0, 1, 0, 0, ...], [0, 0, 0, 0, 0, 1, ...], [0, 1, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], ...], [2, 4, 1, 20], 1, [1, 3, 1, 10], 0, ...]

    def save_game(game):
        rat_hp = str(game[RAT_INDEX][3])
        hero_hp = str(game[HERO_INDEX][3])
        day = str(game[DAY_INDEX])
        x = str(game[X_INDEX])
        y = str(game[Y_INDEX])
        state = str(game[STATE_INDEX])
    
        game_data = [state, hero_hp, day, rat_hp, x, y]
&gt;       game_file = open(GAME_FILE_NAME, 'w')
E       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'

code\new_save_exit_game.py:200: FileNotFoundError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves_and_save" file="code\test_moves_and_save.py" line="84" name="test_save_game_x" time="0.001"><failure message="FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'">def test_save_game_x():#Tests if the correct x coordinate is saved
        rat_hp = 10
        hero_hp = 20
        day = 1
        x = 0 #By default x = 0
        y = 0
        state = 0
&gt;       result = save_game(game)

code\test_moves_and_save.py:92: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

game = [0, [[1, 0, 0, 0, 0, 0, ...], [0, 0, 0, 1, 0, 0, ...], [0, 0, 0, 0, 0, 1, ...], [0, 1, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], ...], [2, 4, 1, 20], 1, [1, 3, 1, 10], 0, ...]

    def save_game(game):
        rat_hp = str(game[RAT_INDEX][3])
        hero_hp = str(game[HERO_INDEX][3])
        day = str(game[DAY_INDEX])
        x = str(game[X_INDEX])
        y = str(game[Y_INDEX])
        state = str(game[STATE_INDEX])
    
        game_data = [state, hero_hp, day, rat_hp, x, y]
&gt;       game_file = open(GAME_FILE_NAME, 'w')
E       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'

code\new_save_exit_game.py:200: FileNotFoundError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_moves_and_save" file="code\test_moves_and_save.py" line="94" name="test_save_game_y" time="0.001"><failure message="FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'">def test_save_game_y():#Tests if the correct y coordinate is saved
        rat_hp = 10
        hero_hp = 20
        day = 1
        x = 0
        y = 0 #By default y = 0
        state = 0
&gt;       result = save_game(game)

code\test_moves_and_save.py:102: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

game = [0, [[1, 0, 0, 0, 0, 0, ...], [0, 0, 0, 1, 0, 0, ...], [0, 0, 0, 0, 0, 1, ...], [0, 1, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], ...], [2, 4, 1, 20], 1, [1, 3, 1, 10], 0, ...]

    def save_game(game):
        rat_hp = str(game[RAT_INDEX][3])
        hero_hp = str(game[HERO_INDEX][3])
        day = str(game[DAY_INDEX])
        x = str(game[X_INDEX])
        y = str(game[Y_INDEX])
        state = str(game[STATE_INDEX])
    
        game_data = [state, hero_hp, day, rat_hp, x, y]
&gt;       game_file = open(GAME_FILE_NAME, 'w')
E       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'

code\new_save_exit_game.py:200: FileNotFoundError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_new_save_exit" file="code\test_new_save_exit.py" line="35" name="test_save_game_day" time="0.001"><failure message="FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'">def test_save_game_day():#Tests if the correct day is saved
        rat_hp = 10
        hero_hp = 20
        day = 1 #By default day = 1
        x = 0
        y = 0
        state = 0
&gt;       result = save_game(game)

code\test_new_save_exit.py:43: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

game = [0, [[1, 0, 0, 0, 0, 0, ...], [0, 0, 0, 1, 0, 0, ...], [0, 0, 0, 0, 0, 1, ...], [0, 1, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], ...], [2, 4, 1, 20], 1, [1, 3, 1, 10], 0, ...]

    def save_game(game):
        rat_hp = str(game[RAT_INDEX][3])
        hero_hp = str(game[HERO_INDEX][3])
        day = str(game[DAY_INDEX])
        x = str(game[X_INDEX])
        y = str(game[Y_INDEX])
        state = str(game[STATE_INDEX])
    
        game_data = [state, hero_hp, day, rat_hp, x, y]
&gt;       game_file = open(GAME_FILE_NAME, 'w')
E       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'

code\new_save_exit_game.py:200: FileNotFoundError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_new_save_exit" file="code\test_new_save_exit.py" line="15" name="test_save_game_game_state" time="0.001"><failure message="FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'">def test_save_game_game_state():#Tests if the correct game state is saved
        rat_hp = 10
        hero_hp = 20
        day = 1
        x = 0
        y = 0
        state = 0 #By default game state is 0
&gt;       result = save_game(game)

code\test_new_save_exit.py:23: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

game = [0, [[1, 0, 0, 0, 0, 0, ...], [0, 0, 0, 1, 0, 0, ...], [0, 0, 0, 0, 0, 1, ...], [0, 1, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], ...], [2, 4, 1, 20], 1, [1, 3, 1, 10], 0, ...]

    def save_game(game):
        rat_hp = str(game[RAT_INDEX][3])
        hero_hp = str(game[HERO_INDEX][3])
        day = str(game[DAY_INDEX])
        x = str(game[X_INDEX])
        y = str(game[Y_INDEX])
        state = str(game[STATE_INDEX])
    
        game_data = [state, hero_hp, day, rat_hp, x, y]
&gt;       game_file = open(GAME_FILE_NAME, 'w')
E       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'

code\new_save_exit_game.py:200: FileNotFoundError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_new_save_exit" file="code\test_new_save_exit.py" line="25" name="test_save_game_hero_hp" time="0.001"><failure message="FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'">def test_save_game_hero_hp():#Tests if the correct hero hp is saved
        rat_hp = 10
        hero_hp = 20 #By default hero hp starts at 20
        day = 1
        x = 0
        y = 0
        state = 0
&gt;       result = save_game(game)

code\test_new_save_exit.py:33: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

game = [0, [[1, 0, 0, 0, 0, 0, ...], [0, 0, 0, 1, 0, 0, ...], [0, 0, 0, 0, 0, 1, ...], [0, 1, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], ...], [2, 4, 1, 20], 1, [1, 3, 1, 10], 0, ...]

    def save_game(game):
        rat_hp = str(game[RAT_INDEX][3])
        hero_hp = str(game[HERO_INDEX][3])
        day = str(game[DAY_INDEX])
        x = str(game[X_INDEX])
        y = str(game[Y_INDEX])
        state = str(game[STATE_INDEX])
    
        game_data = [state, hero_hp, day, rat_hp, x, y]
&gt;       game_file = open(GAME_FILE_NAME, 'w')
E       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'

code\new_save_exit_game.py:200: FileNotFoundError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_new_save_exit" file="code\test_new_save_exit.py" line="45" name="test_save_game_rat_hp" time="0.001"><failure message="FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'">def test_save_game_rat_hp():#Tests if the correct rat hp is saved
        rat_hp = 10 #By default rat hp = 10
        hero_hp = 20
        day = 1
        x = 0
        y = 0
        state = 0
&gt;       result = save_game(game)

code\test_new_save_exit.py:53: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

game = [0, [[1, 0, 0, 0, 0, 0, ...], [0, 0, 0, 1, 0, 0, ...], [0, 0, 0, 0, 0, 1, ...], [0, 1, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], ...], [2, 4, 1, 20], 1, [1, 3, 1, 10], 0, ...]

    def save_game(game):
        rat_hp = str(game[RAT_INDEX][3])
        hero_hp = str(game[HERO_INDEX][3])
        day = str(game[DAY_INDEX])
        x = str(game[X_INDEX])
        y = str(game[Y_INDEX])
        state = str(game[STATE_INDEX])
    
        game_data = [state, hero_hp, day, rat_hp, x, y]
&gt;       game_file = open(GAME_FILE_NAME, 'w')
E       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'

code\new_save_exit_game.py:200: FileNotFoundError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_new_save_exit" file="code\test_new_save_exit.py" line="55" name="test_save_game_x" time="0.001"><failure message="FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'">def test_save_game_x():#Tests if the correct x coordinate is saved
        rat_hp = 10
        hero_hp = 20
        day = 1
        x = 0 #By default x = 0
        y = 0
        state = 0
&gt;       result = save_game(game)

code\test_new_save_exit.py:63: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

game = [0, [[1, 0, 0, 0, 0, 0, ...], [0, 0, 0, 1, 0, 0, ...], [0, 0, 0, 0, 0, 1, ...], [0, 1, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], ...], [2, 4, 1, 20], 1, [1, 3, 1, 10], 0, ...]

    def save_game(game):
        rat_hp = str(game[RAT_INDEX][3])
        hero_hp = str(game[HERO_INDEX][3])
        day = str(game[DAY_INDEX])
        x = str(game[X_INDEX])
        y = str(game[Y_INDEX])
        state = str(game[STATE_INDEX])
    
        game_data = [state, hero_hp, day, rat_hp, x, y]
&gt;       game_file = open(GAME_FILE_NAME, 'w')
E       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'

code\new_save_exit_game.py:200: FileNotFoundError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="code.test_new_save_exit" file="code\test_new_save_exit.py" line="65" name="test_save_game_y" time="0.001"><failure message="FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'">def test_save_game_y():#Tests if the correct y coordinate is saved
        rat_hp = 10
        hero_hp = 20
        day = 1
        x = 0
        y = 0 #By default y = 0
        state = 0
&gt;       result = save_game(game)

code\test_new_save_exit.py:73: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

game = [0, [[1, 0, 0, 0, 0, 0, ...], [0, 0, 0, 1, 0, 0, ...], [0, 0, 0, 0, 0, 1, ...], [0, 1, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], [0, 0, 0, 0, 0, 0, ...], ...], [2, 4, 1, 20], 1, [1, 3, 1, 10], 0, ...]

    def save_game(game):
        rat_hp = str(game[RAT_INDEX][3])
        hero_hp = str(game[HERO_INDEX][3])
        day = str(game[DAY_INDEX])
        x = str(game[X_INDEX])
        y = str(game[Y_INDEX])
        state = str(game[STATE_INDEX])
    
        game_data = [state, hero_hp, day, rat_hp, x, y]
&gt;       game_file = open(GAME_FILE_NAME, 'w')
E       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ETI\\Testing\\game_data.txt'

code\new_save_exit_game.py:200: FileNotFoundError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>